
name: CI

on:
  push:
    branches: [ master, pre-workflow, stable/0.3.x ]
  pull_request:

# Current configuration:
# - django 2.2, python 3.6, wagtail 2.6, postgres
# - django 2.2, python 3.7, wagtail 2.7, postgres
# - django 3.0, python 3.8, wagtail 2.8, postgres
# - django 3.0, python 3.8, wagtail 2.8, sqlite
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
          - python: 3.6
            django: "Django>=2.2,<2.3"
            wagtail: "wagtail>=2.6,<2.7"
            database: "postgresql"
            experimental: false
          - python: 3.7
            django: "Django>=2.2,<2.3"
            wagtail: "wagtail>=2.7,<2.8"
            database: "postgresql"
            experimental: false
          - python: 3.8
            django: "Django>=3.0,<3.1"
            wagtail: "wagtail>=2.8,<2.9"
            database: "postgresql"
            experimental: false
          - python: 3.8
            django: "Django>=3.0,<3.1"
            wagtail: "wagtail>=2.8,<2.9"
            database: "sqlite3"
            experimental: false

    services:
      postgres:
        image: postgres:10.8
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "psycopg2>=2.6"
          pip install "${{ matrix.django }}"
          pip install "${{ matrix.wagtail }}"
          pip install -e .[testing]
      - name: Test
        run: ./runtests.py
        env:
          DATABASE_ENGINE: django.db.backends.${{ matrix.database }}
          DATABASE_HOST: localhost
          DATABASE_USER: postgres
          DATABASE_PASS: postgres
